version: "3.7"

services:

  # PHP FPM
  php-fpm:
    build: './docker/php-fpm'
    container_name: online_education_php-fpm
    volumes:
      - ./:/var/www/app
    working_dir: /var/www/app

  # Nginx
  nginx:
    image: nginx:1.15
    container_name: online_education_nginx
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/app
    ports:
      - 8080:80
    depends_on:
      - php-fpm

  composer:
    image: "composer"
    volumes:
      - ./:/app
    command: install

  # MySQL
  mysql:
    image: mysql:8.0
    container_name: online_education_mysql
    volumes:
      - ./var/mysql:/var/lib/mysql
    ports:
      - 3307:3306
    env_file:
      - '.env.local'
