version: '3'

services:

  php:
    build:
      context: ./docker/php
    ports:
      - 9000:9000
    volumes:
      - ./:/online_education
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    links:
      - mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  nginx:
    image: nginx:1.15
    container_name: online_education
    ports:
      - 8080:80
      - 9001:9001
    volumes:
      - ./:/online_education
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

  composer:
    image: "composer"
    volumes:
      - ./:/app
    command: install

  mysql:
    image: mysql:8.0
    container_name: online_education-mysql
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "8989:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - ./mysql:/etc/msql/conf.d/*:ro
